### ISSUE TITLE
SSL Cert Expired

### ISSUE THREAD

**Issue by KrotonGG** [SealSlicer/OmgSpidersGuild#5]
,s{{{}}}s
             ,{{{}}}}}}{},
            {{{{,}}}}}}}}}}
           ,"   }{}}}{},{{}}
          {{~  ~{  }}{/ )}}}
           `/   }    `,J{{{{
            `   `    (  )}}
             \=-  _,-'`" {{{_
           ,--`-="  `-._,'   `--.,
          /   \\    __            \
         /    /;_,-'--'            :
        /    /   ,-"--'         \   :
       /    /   _,--="          ,   |
      /    ;  ;" o   '        o `   |
     /   ,'  ;\       :  \       )  :
    / ,-'  ,'| `. __,'    `. __,'\   :

**Comment by SealSlicer** [comment]
resolved by generating using Let's Encrypt thru azure portal
